@startuml UC5: Manage Orders - Reject Order

!theme plain

autonumber

actor User
participant "System" as System
participant "Server" as Server

== Reject Order ==

User -> System: Press "Reject Order" Button
System -> Server: Request Order Rejection
Server -> Server: Check Order
Server -> Server: Update Order Status to Rejected
Server -> System: Rejection Complete
System -> User: Display Rejection Complete Message

@enduml
